spring:
  application:
    name: tlias-web-managerment
  #配置数据库的连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大请求大小（包括所有文件和表单数据大小 ）
      max-request-size: 100MB
#mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射的开关，将xxxa_bxxx <-> xxxaBxxx(将数据库的字段名和实体类中的属性名进行映射)
    map-underscore-to-camel-case: true
#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#aliy
aliyun:
  oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: java-ai-lyuce
      region: cn-beijing
